services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html/trayChallengeMarketplace
    working_dir: /var/www/html/trayChallengeMarketplace
    depends_on:
      - mysql
    networks:
      - laravel-network
    ports:
      - "8080:80"

  mysql:
    image: mysql:latest
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=marketplace_connector
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - laravel-network

  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon_server
    ports:
      - "3000:3000"
    volumes:
      - ./mocketplace.json:/data
    command: -d /data -p 3000
    networks:
      - laravel-network

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
