services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www/html/trayChallengeMarketplace
    working_dir: /var/www/html/trayChallengeMarketplace
    networks:
      - laravel-network
    ports:
      - "8080:80" 

  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon_server
    ports:
      - "3000:3000"
    volumes:
      - ./mocketplace.json:/data
    command: -d /data -p 3000
    networks:
      - laravel-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel-network

networks:
  laravel-network:
